import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 开源生态产品线侧边栏（实例 id: opensource）
const sidebars: SidebarsConfig = {
  opensourceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
