import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 新品产品线侧边栏（实例 id: newproducts）
const sidebars: SidebarsConfig = {
  newproductsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
