import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 独立传感器产品线侧边栏（实例 id: sensors）
const sidebars: SidebarsConfig = {
  sensorsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
