import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 配件产品线侧边栏（实例 id: accessories）
const sidebars: SidebarsConfig = {
  accessoriesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
