import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 模组产品线侧边栏（实例 id: modules）
const sidebars: SidebarsConfig = {
  modulesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
