import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 侧边栏采用「按目录自动生成」策略：
 * 目录结构 + 每个目录下的 _category_.json 共同决定侧边栏的层级、顺序与显示名称。
 * 新增文档只需在对应目录放入 .md / .mdx 文件即可，无需改本文件。
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
